/**
 * 手动触发全流程并输出每日研报
 *
 * 用法:
 *   npm run report                         # 采集 → 生成 → 推送 → 终端输出
 *   npm run report -- --no-push            # 跳过推送（预览模式，不标记已报告）
 *   npm run report -- --report-only        # 仅用已有数据生成（不采集）
 *   npm run report -- --json               # JSON 格式输出
 *   npm run report -- --output report.md   # 写入文件
 *   npm run report -- --help               # 查看帮助
 */

import * as fs from 'fs';
import * as path from 'path';
import { DeepCurrentsEngine } from './monitor';
import { DailyReport } from './services/ai.service';
import { THREAT_LABELS, ThreatLevel } from './services/classifier';

// ── CLI 参数解析 ──

const argv = process.argv.slice(2);

function flagValue(name: string): string | null {
  const idx = argv.indexOf(name);
  return idx >= 0 && idx + 1 < argv.length ? argv[idx + 1]! : null;
}

const opts = {
  json:       argv.includes('--json'),
  noPush:     argv.includes('--no-push'),
  reportOnly: argv.includes('--report-only'),
  output:     flagValue('--output'),
  help:       argv.includes('--help') || argv.includes('-h'),
};

// ── 帮助信息 ──

if (opts.help) {
  console.log(`
🌊 DeepCurrents — 手动触发每日研报

用法:
  npm run report [-- <options>]
  npx ts-node src/run-report.ts [<options>]

选项:
  --report-only   仅基于已采集的数据生成研报（跳过 RSS 采集）
  --no-push       不推送到飞书/Telegram，不标记新闻为已报告（预览模式）
  --json          以 JSON 格式输出研报
  --output <path> 将研报写入指定文件（不写 stdout）
  --help, -h      显示帮助信息

示例:
  npm run report                                    # 完整流程
  npm run report -- --no-push                       # 预览，不推送
  npm run report -- --report-only --json            # 用已有数据生成 JSON
  npm run report -- --output data/reports/today.md  # 写入文件
`.trimStart());
  process.exit(0);
}

// ── 研报格式化 ──

function formatMarkdown(
  report: DailyReport,
  meta: { newsCount: number; clusterCount: number },
): string {
  const L: string[] = [];

  L.push(`# 🌊 DeepCurrents 每日全球情报与宏观策略`);
  L.push('');
  L.push(`**日期**: ${report.date}  `);
  L.push(`**数据源**: ${meta.newsCount} 条新闻 → ${meta.clusterCount} 个聚类事件`);
  L.push('');
  L.push('---');
  L.push('');

  L.push(`## 核心主线 | Executive Summary`);
  L.push('');
  L.push(report.executiveSummary);
  L.push('');

  L.push(`## 重大事件 | Key Events`);
  L.push('');
  report.globalEvents.forEach((e, i) => {
    const icon = e.threatLevel
      ? (THREAT_LABELS[e.threatLevel as ThreatLevel] ?? '') + ' '
      : '';
    L.push(`${i + 1}. ${icon}**${e.title}**: ${e.detail}`);
  });
  L.push('');

  if (report.trendingAlerts && report.trendingAlerts.length > 0) {
    L.push(`## 趋势告警 | Trending Alerts`);
    L.push('');
    for (const a of report.trendingAlerts) {
      const sig = a.significance === 'high' ? '🔴' : a.significance === 'medium' ? '🟡' : '🟢';
      L.push(`- ${sig} **${a.term}**: ${a.assessment}`);
    }
    L.push('');
  }

  L.push(`## 宏观趋势深度研判 | Deep Insights`);
  L.push('');
  L.push(report.economicAnalysis);
  L.push('');

  L.push(`## 资产配置与投资风向 | Investment Strategy`);
  L.push('');
  report.investmentTrends.forEach(t => {
    const icon = t.trend === 'Bullish' ? '🟢 看涨' : t.trend === 'Bearish' ? '🔴 看跌' : '⚪ 中性';
    const conf = t.confidence != null ? ` (${t.confidence}%)` : '';
    L.push(`- **${t.assetClass}** ${icon}${conf}: ${t.rationale}`);
  });
  L.push('');

  if (report.riskAssessment) {
    L.push(`## 风险评估 | Risk Assessment`);
    L.push('');
    L.push(report.riskAssessment);
    L.push('');
  }

  L.push('---');
  L.push(`*Generated by DeepCurrents Intelligence v2.1*`);
  L.push('');
  return L.join('\n');
}

// ── 输出 ──

function writeOutput(content: string, filePath: string | null): void {
  if (filePath) {
    const dir = path.dirname(path.resolve(filePath));
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.resolve(filePath), content, 'utf-8');
    console.error(`✅ 研报已写入 ${path.resolve(filePath)}`);
  } else {
    console.log(content);
  }
}

// ── 主流程 ──

async function main() {
  const engine = new DeepCurrentsEngine();

  // 1. 采集（除非 --report-only）
  if (!opts.reportOnly) {
    console.error('📡 正在采集全球信息源...');
    const stats = await engine.collectData();
    console.error(
      `📡 采集完成 — 新增 ${stats.newItems} | 跳过 ${stats.skippedSources} | ` +
      `错误 ${stats.errors} | 趋势飙升 ${stats.spikeCount}`,
    );
  }

  // 2. 生成研报
  console.error('🧠 正在生成研报...');
  const result = await engine.generateReport();
  if (!result) {
    console.error('⚠️  无新数据，未生成研报。');
    process.exit(1);
  }
  console.error(
    `🧠 研报生成完成 — ${result.newsCount} 条新闻 → ${result.clusterCount} 个聚类事件`,
  );

  // 3. 推送（除非 --no-push）
  if (!opts.noPush) {
    console.error('📤 正在推送研报...');
    await engine.deliverReport(result.report, result.newsCount, result.clusterCount);
    engine.markNewsAsReported(result.newsIds);
    console.error('📤 推送完成，新闻已标记为已报告。');
  } else {
    console.error('⏭️  跳过推送（--no-push），新闻未标记为已报告。');
  }

  // 4. 格式化输出
  const content = opts.json
    ? JSON.stringify(result.report, null, 2)
    : formatMarkdown(result.report, { newsCount: result.newsCount, clusterCount: result.clusterCount });

  writeOutput(content, opts.output);
}

main()
  .then(() => setTimeout(() => process.exit(0), 100))
  .catch(e => {
    console.error(`❌ 执行失败: ${e.message}`);
    setTimeout(() => process.exit(1), 100);
  });
